apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    app: mi-app
  ports:
    - port: 80 # Puerto que se usa para acceder
      targetPort: 5000 # Puerto interno de Flask (containerPort)
  type: LoadBalancer # O NodePort si estamos en un entorno local (MiniKube)