apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: crud-namespace # En el namespace
  labels:
    app: postgres
spec:
  replicas: 1 # Un solo Pod para la BD
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            # Los valores deben coincidir con app.py
            - name: POSTGRES_DB
              value: "appdb"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: crud-namespace # En el namespace
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Solo accesible por el nombre 'postgres-service' dentro del clúster