apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres # Debe coincidir con el label del Pod de la BD (Paso 2)
  ports:
    - port: 5432
      targetPort: 5432