apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: crud-namespace
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15 # Versión de PostgreSQL
      ports:
        - containerPort: 5432 # Puerto estándar de PostgreSQL
      env:
        - name: POSTGRES_DB
          value: "appdb" # Nombre de la BD
        - name: POSTGRES_USER
          value: "user" # Usuario
        - name: POSTGRES_PASSWORD
          value: "mypassword" # Contraseña
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        - mountPath: /docker-entrypoint-initdb.d/
          name: init-script
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pv-claim
    - name: init-script
      configMap:
        name: postgres-init-script
